name: renew
channels:
  - conda-forge
dependencies:
  - aiohttp
  - black
  - bokeh
  - bottleneck
  - cartopy
  - cftime
  - dask
  - dask-labextension
  - distributed
  - fsspec<2025
  - gdal
  - geopandas
  - geos
  - geotiff
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ipython
  - isort
  - jupyterlab
  - jupyterlab_widgets
  - libgdal
  - matplotlib
  - mpich
  - nbqa
  - netcdf4
  - nodejs>=18
  - numba
  - numpy<2.0
  - packaging>=24.0,<25.0
  - pandas
  - pip
  - pooch
  - pre-commit
  - proj
  - pyproj
  - pytables
  - pytest
  - pytest-cov
  - python=3.9
  - rasterio
  - requests
  - rioxarray
  - ruff
  - scikit-learn
  - scipy
  - seaborn
  - conda-forge:setuptools<81
  - shapely
  - statsmodels
  - tqdm
  - conda-forge:wrf-python
  - xarray>=2024.06
  - xclim
  - zarr>=2.17,<3
  - pip:
    - aiobotocore
    - aioboto3
    - geopandas
    - dask_geopandas
    - kerchunk
    - simplempi
    - pint
    - pyogrio
    - NREL-rex
    - numpy==1.26.4
    - s3fs
    - tables
    - ypy-websocket
